CREATE DATABASE IF NOT EXISTS db_projeto;

USE db_projeto;

CREATE TABLE tb_animal (
  ID_codigo INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(20) NOT NULL,
  Sobrenome VARCHAR(150) NOT NULL,
  Raca VARCHAR(20) NULL,
  Tipo VARCHAR(20) NULL,
  Idade INT NULL,
  Alergico VARCHAR(5) NULL,
  Cliente VARCHAR(20) NOT NULL
);

CREATE TABLE tb_cliente (
  ID_codigo INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(50)  NOT NULL,
  Sobrenome VARCHAR(150) NULL,
  Endereco VARCHAR(255) NULL,
  Cidade VARCHAR(45) NULL,
  Telefone VARCHAR(20) NULL,
  Celular VARCHAR(20) NULL,
  CPF VARCHAR(15)  NOT NULL UNIQUE,
  RG VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE tb_consulta (
  ID_codigo INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Datahora DATETIME NULL,
  Diagnostico VARCHAR(20) NULL,
  Valor FLOAT(10) NULL,
  Peso FLOAT(10) NULL,
  Altura FLOAT(10) NULL,
  Veterinario VARCHAR(20) NOT NULL,
  Animal VARCHAR(20) NOT NULL
);

CREATE TABLE tb_usuario (
  ID_codigo INT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(45) NOT NULL,
  Sobrenome VARCHAR(150) NOT NULL,
  Email VARCHAR(50) NOT NULL UNIQUE,
  Senha VARCHAR(20)  NOT NULL,
  CRV VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE tb_veterinario (
  ID_CRV INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(50) NOT NULL,
  Sobrenome VARCHAR(150) NOT NULL,
  Cidade VARCHAR(45) NULL,
  Endereco VARCHAR(255) NULL,
  Celular VARCHAR(20) NULL,
  CPF VARCHAR(15) NOT NULL UNIQUE
);


